name: 'Okteto Build'
description: 'Build an image from a Dockerfile using Okteto Cloud'
inputs:
  tag:
    description: 'Name and tag in the "name:tag" format'
    required: false
  file:
    description: 'Name of the Okteto Manifest or Dockerfile'
    required: false
  path:
    description: 'The path'
    required: false
    default: '.'
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.file }}
    - ${{ inputs.path }}
    - ${{ inputs.buildargs }}
branding:
  color: 'green'
  icon: 'layers'