name: 'Okteto Build'
description: 'Build an image from a Dockerfile using Okteto Cloud'
inputs:
  tag:
    description: 'Name and tag for the image in the "name:tag" format'
    required: false
  file:
    description: 'Name of the file for Okteto Manifest or Dockerfile.'
    required: false
  path:
    description: 'Path where the build is run.'
    required: false
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.file }}
    - ${{ inputs.path }}
    - ${{ inputs.buildargs }}
branding:
  color: 'green'
  icon: 'layers'