name: 'Okteto Build'
description: 'Build an image from a Dockerfile using Okteto Cloud'
inputs:
  file:
    description: 'The path to the Okteto Manifest. Default `'okteto.yml'`
    required: false
    default: 'okteto.yml'
  services:
    description: 'Services to build. If none, all images at the okteto manifest will be built.'
    required: false
  global:
    description: 'Use global when you want to make the image availbale to everyone in your team'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.services }}
    - ${{ inputs.global }}
branding:
  color: 'green'
  icon: 'layers'
