name: 'Okteto Build'
description: 'Build an image from a Dockerfile using Okteto Cloud'
inputs:
  tag:
    description: 'Name and tag for the image in the "name:tag" format'
    required: false
  file:
    description: 'Name of the file for the Okteto Manifest or Dockerfile.'
    required: false
  path:
    description: 'Path where the build is run.'
    required: false
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
  target:
    description: 'Use specific target stage to build image'
    required: false
  no-cache:
    description: 'Do not use cache when building the image'
    required: false
  cache-from:
    description: 'List of cache source images'
    required: false
  export-cache:
    description: 'List of exported cache images'
    required: false
  secrets:
    description: 'Secret files exposed to the build. Format: id=mysecret,src=/local/secret'
    required: false
  platform:
    description: 'Set target platform for build'
    required: false
  log-level:
    description: "Log level string. Valid options are debug, info, warn, error"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.file }}
    - ${{ inputs.path }}
    - ${{ inputs.buildargs }}
    - ${{ inputs.no-cache }}
    - ${{ inputs.cache-from }}
    - ${{ inputs.export-cache }}
    - ${{ inputs.secrets }}
    - ${{ inputs.platform }}
    - ${{ inputs.log-level }}  

branding:
  color: 'green'
  icon: 'layers'